### PR TITLE
Adding Data Structure Implementations in C++

### PR DESCRIPTION
**Pull request by erdanielx**
I created a library of many Data Structures that we have seen in class and
implemented for homeworks in C++.

### CODE REVIEW

**Comment by florian-rabe** [comment]
I awarded 3% bonus credit for this contribution.

**Comment by florian-rabe** [comment]
What's your real name (so that I can record the bonus credit)?

**Comment by erdanielx** [comment]
I am Daniel Nieto Rodriguez

**Comment by florian-rabe** [comment]
OK

**Pull request merged**
