### PR TITLE
Some additional information about the mathematical background of cryptography. 

### PR DESCRIPTION
**Pull request by ColinRothgang**
It might still be nice to extend this even further later on.

### CODE REVIEW

**Comment by florian-rabe** [comment]
Wow, quite impressive.
I'll have to read it in detail before reacting.

The second commit causes conflicts - can you take it out? (In general, it's easier to exclude the pdf files from the commits.)

**Comment by ColinRothgang** [comment]
It should be fine now.

**Comment by florian-rabe** [comment]
Github still doesn't let me merge automatically.

Maybe I've pushed new commits by now that create another conflict?

**Comment by ColinRothgang** [comment]
The problem were the deleted pdf files. I recreated them now, so the conflicts are solved.

**Comment by florian-rabe** [comment]
I merged it right away to avoid further conflicts.

Somehow a pdf file (AaDS homework) was deleted in your changes. I restored it and hope it was the only hickup.

I added a disclaimer to the section because I haven't had time to read it yet.
We should discuss it together next week.

**Pull request merged**
